service: api-gateway # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6

# you can overwrite defaults here
stage: production
functions:
  readCustomer:
    handler: handler.gateway
    events:
      - http:
          path: book/create
          method: post
          
      - http:
          path: sell/book
          method: post