
service: api-gateway-and-lambdas

provider:
  name: aws
  runtime: python3.8
  region: 'us-east-1'
  memorySize: 128
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sns:*'
      Resource:
        - 'arn:aws:sns:us-east-1:644689573437:sns-1-topic'
        # -  '<ARN-SNS-AQUI>'

package:
  exclude:
    - "node_modules/*"
    - "./node_modules/**"
    - layer/**
    - schemas/*
    
layers:
  LayerDependencies:
    path: layer
    description: "learning layers"

functions:
  book-create:
    handler: book_create.handler
    
    events:
      - http:
          path: /book/create
          method: post
          cors: true
          request:
            schema:
              application/json: ${file(schemas/book-create-schema-request.json)}
              
    layers:
      - {Ref: LayerDependenciesLambdaLayer}

    environment:
      # snsArn: '<ARN-SNS-AQUI>'
      snsArn: 'arn:aws:sns:us-east-1:644689573437:sns-1-topic'
      